### ISSUE TITLE
Navbar Dropdown menu

### ISSUE THREAD

**Issue by NeverEverAlone** [yyenph/NeverEverAlone#11]
Navbar structure is built, but each navbar item has more items, thus, building drop down menu is needed

- [x] Home: Leave it as it is now
- [x] Domestic Violence: Types, Causes, Solution
- [x] About: Founder, Vision, Mission, Team (name, pic, linkedin)
- [x] Contact: leave it as it is now
- [x] Download App: leave it as it is now

**Comment by NeverEverAlone** [comment]
Yen has used tailwind to build drop down menus.

**Comment by yyenph** [comment]
completed
