### ISSUE TITLE
Home page building

### ISSUE THREAD

**Issue by NeverEverAlone** [yyenph/NeverEverAlone#12]
Building home page (Home.jsx under src/page folder) following figma deign (https://www.figma.com/file/DhJMpq7HotOAtH1jgwoU0v/Nevereveralone?node-id=1839%3A12476&mode=dev)
Here is the link for different sections and file names:
https://www.figma.com/file/gmtMORaiJyRA6K8F7zx5Ov/nea-web-components-division?type=whiteboard&node-id=727-97&t=QWRmC5XEBGnlk1ii-0

to do:
- [x] Contact.jsx
- [x] footer.jsx

**Comment by yyenph** [comment]
Added contact and footer. Contact form is working.
