### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by NeverEverAlone** [yyenph/NeverEverAlone#13]
Build contact form in Contact.jsx 

- [ ] build contact form in Contact.jsx
- [ ] link Contact.jsx to navbar item "Contact"

Resource:
https://react-hook-form.com/
https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/
(or any other libraries you would like to explore)

**Comment by yyenph** [comment]
Complete
